♻Code refactoring

diff --git a/.github/workflows/test_multi_os.yml b/.github/workflows/test_multi_os.yml
--- a/.github/workflows/test_multi_os.yml
+++ b/.github/workflows/test_multi_os.yml
@@ -73,7 +73,7 @@ jobs:
         shell: bash
         run: |
           echo "System date: $(date)"
-          echo "TZ environment variable: $TZ"
+          echo "TZ environment variable: ${TZ}"
           python -c "import datetime, platform; print(f'Python timezone: {datetime.datetime.now().astimezone().tzinfo}'); print(f'OS: {platform.system()}')"
       - name: Install poetry
         run: pip install poetry
@@ -146,8 +146,8 @@ jobs:
           python_versions='${{ needs.set_variables.outputs.versions_python }}'
 
           # JSON形式の文字列から配列を作成
-          os_list=$(echo "$os" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
-          python_versions_list=$(echo "$python_versions" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
+          os_list=$(echo "${os}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
+          python_versions_list=$(echo "${python_versions}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
 
           # "coverage" ブランチが存在する場合はチェックアウト、存在しない場合は新規作成する
           if git ls-remote --heads origin coverage | grep coverage; then
@@ -160,45 +160,45 @@ jobs:
           # README.mdの内容を一度に生成
           {
             echo "# Pytest Coverages Summary"
-            echo "[![](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml/badge.svg)](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml)"
+            echo "[![](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/test_multi_os.yml/badge.svg)](https://github.com/${GITHUB_REPOSITORY}/actions/workflows/test_multi_os.yml)"
             echo ""
 
             # 最新のコミット情報をREADMEに追加
             commit_hash8=${GITHUB_SHA::8}
-            commit_link="[$commit_hash8](https://github.com/$GITHUB_REPOSITORY/tree/$commit_hash8)"
+            commit_link="[${commit_hash8}](https://github.com/${GITHUB_REPOSITORY}/tree/${commit_hash8})"
             echo -e "> [!Note]"
             echo -e "> "
-            echo -e "> Commit: $commit_link"
+            echo -e "> Commit: ${commit_link}"
             echo -e ""
 
             # テスト対象外のファイルに関する注記を追加（ファイルの存在確認結果に基づく）
             commit_hash=${GITHUB_SHA}
             file_path_1="project_a/staking/ton_whales_staking_dashboard.py"
             file_path_2="staking/ton_whales_staking_dashboard.py"
-            file_link="https://github.com/$GITHUB_REPOSITORY/blob/$commit_hash/$file_path_2"
+            file_link="https://github.com/${GITHUB_REPOSITORY}/blob/${commit_hash}/${file_path_2}"
 
             if [[ "${{ needs.check_file.outputs.file_exists }}" == "true" ]]; then
               echo -e "> [!Important]"
               echo -e "> The following file is intentionally excluded from test coverage:"
-              echo -e "> - [$file_path_1]($file_link)"
+              echo -e "> - [${file_path_1}](${file_link})"
               echo -e "> "
               echo -e "> This file contains complex external dependencies and is verified through manual and integration testing."
               echo -e "> "
             else
-              echo "Note: File $file_path_1 not found. Skipping addition to README.md." >&2
+              echo "Note: File ${file_path_1} not found. Skipping addition to README.md." >&2
             fi
 
             # macOS、Ubuntu、Windowsの各OSとPythonバージョンごとにカバレッジレポートを追加
-            for os in $os_list; do
-              for version in $python_versions_list; do
-                echo "## Coverage Report (os: $os / python-version: $version)"
-                if [ -f "coverage-data-$os-$version/summary-report.md" ]; then
-                  sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' -e 's/\\\\/\\/g' -e 's/\\n/\n/g' -e 's/\r$//' "coverage-data-$os-$version/summary-report.md" |
+            for os in ${os_list}; do
+              for version in ${python_versions_list}; do
+                echo "## Coverage Report (os: ${os} / python-version: ${version})"
+                if [ -f "coverage-data-${os}-${version}/summary-report.md" ]; then
+                  sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' -e 's/\\\\/\\/g' -e 's/\\n/\n/g' -e 's/\r$//' "coverage-data-${os}-${version}/summary-report.md" |
                   sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' |
                   sed '/^$/N;/^\n$/D' |
                   sed -e 's/^"//' -e 's/"$//'
                 else
-                  echo "No summary report found for $os - $version"
+                  echo "No summary report found for ${os} - ${version}"
                 fi
                 echo ""
               done
@@ -207,7 +207,7 @@ jobs:
 
           # カバレッジレポート内のリンクを有効にするためにファイルパスを修正する
           sed -i '
-            s|/blob/undefined/\([^"]*\)|/blob/'"$commit_hash"'/\1|g;
+            s|/blob/undefined/\([^"]*\)|/blob/'"${commit_hash}"'/\1|g;
             s|/blob/\([a-f0-9]*\)/\([^"]*\)|/blob/\1/project_a/\2|g;
             s|/blob/\([a-f0-9]*\)/project_a/README\.md|/blob/\1/README.md|g
           ' README.md
